translations = {
    "ru": {
        "menu.header": "CryonixSoft",
        "menu.title": "Меню чекера сессий",
        "menu.start_process": "[1] Запустить проверку сессий",
        "menu.change_language": "[2] Сменить язык",
        "menu.configure_settings": "[3] Настроить параметры",
        "menu.exit": "[4] Выход",
        "menu.select_option": "Выберите опцию [1-4]:",
        "menu.press_enter": "Нажмите Enter для продолжения...",
        "menu.starting_process": "Запуск проверки сессий...",
        "menu.process_completed": "Проверка завершена успешно",
        "menu.process_failed": "Некоторые сессии неавторизованы или с ошибками",
        "menu.goodbye": "До свидания!",
        "menu.language_changed": "Язык изменён на {language}",
        "menu.select_language": "Выберите язык",
        "menu.select_language_option": "Выберите опцию [0-2]:",
        "menu.back": "[0] Назад",
        "menu.proxy_error": "Ошибка: {error}. Прокси необходим для проверки.",
        "menu.no_json_files": "Не найдено JSON-файлов в {dir}",
        "menu.error": "Ошибка: {error}",
        "menu.running": "Процесс уже выполняется",
        "menu.config_created": "Создан файл конфигурации {file}",
        "menu.dir_created": "Создана папка {dir}",
        "menu.proxy_file_created": "Создан файл прокси {file}",
        "menu.auth_data_missing_creating": "JSON-файл {file} отсутствует, создаётся новый",
        "menu.auth_data_created": "JSON-файл {file} создан",
        "menu.api_data_missing_generating": "API данные отсутствуют в {file}, генерируются новые",
        "menu.api_data_generated": "API данные сгенерированы для {file}",
        "menu.phone_missing": "Номер телефона отсутствует в {file}",
        "menu.api_data_missing": "Недостаточно данных API в {file}",
        "menu.session_missing": "Сессия для {phone} не найдена",
        "menu.using_proxy_old": "Используется прокси: {host}:{port}",
        "menu.no_proxy_old": "Прокси не используются для {phone}",
        "menu.session_authorized": "Сессия для {phone} авторизована",
        "menu.session_not_authorized": "Сессия для {phone} не авторизована",
        "menu.session_file_moved": "Файл сессии {file} перемещён в unauthorized_sessions",
        "menu.json_file_moved": "JSON-файл {file} перемещён в unauthorized_sessions",
        "menu.flood_limit": "Ограничение Telegram API для {phone}, ожидание {seconds} секунд",
        "menu.session_unregistered": "Сессия для {phone} не зарегистрирована",
        "menu.session_error": "Ошибка при обработке сессии для {phone}: {error}",
        "menu.connection_failed": "Не удалось подключиться для {phone}: {error}",
        "menu.main_error": "Произошла ошибка: {error}",
        "menu.current_max_threads": "Текущее количество потоков: {value}",
        "menu.enter_max_threads": "Введите количество потоков (мин. 1):",
        "menu.max_threads_updated": "Количество потоков обновлено: {value}",
        "menu.select_setting_option": "Выберите параметр для настройки [0-1]:",
        "error.proxy_empty": "Файл proxy.txt пуст или отсутствует",
        "log.config_file_missing": "Файл {file} не найден, создаётся с настройками по умолчанию",
        "log.dir_created": "Создана папка: {dir}",
        "log.proxy_file_created": "Создан файл proxy.txt с примером формата",
        "log.invalid_proxy_format": "Некорректный формат строки в proxy.txt: {line}",
        "log.proxy_file_empty": "Файл {file} пуст, прокси необходим",
        "log.auth_data_missing_creating": "JSON-файл {file} отсутствует, создаётся новый",
        "log.auth_data_created": "JSON-файл {file} создан",
        "log.api_data_missing_generating": "API данные отсутствуют в {file}, генерируются новые",
        "log.api_data_generated": "API данные сгенерированы для {file}",
        "log.phone_missing": "Номер телефона отсутствует в {file}",
        "log.api_data_missing": "Недостаточно данных API в {file}: api_id или api_hash отсутствуют",
        "log.session_missing": "Сессия для {phone} не найдена",
        "log.using_proxy_old": "Используется прокси: {host}:{port}",
        "log.no_proxy_old": "Прокси не используются для {phone}",
        "log.session_authorized": "Сессия для {phone} авторизована",
        "log.session_not_authorized": "Сессия для {phone} не авторизована",
        "log.session_file_moved": "Файл сессии {file} перемещён в unauthorized_sessions",
        "log.json_file_moved": "JSON-файл {file} перемещён в unauthorized_sessions",
        "log.flood_limit": "Ограничение Telegram API для {phone}, требуется ожидание {seconds} секунд",
        "log.session_unregistered": "Сессия для {phone} не зарегистрирована",
        "log.session_error": "Ошибка при обработке сессии для {phone}: {error}",
        "log.connection_failed": "Не удалось подключиться для {phone}: {error}",
        "log.changing_language": "Смена языка",
        "log.language_changed": "Язык изменён на {language}",
        "log.option_selected": "Выбрана опция: {choice}",
        "log.main_error": "Произошла ошибка: {error}",
        "log.configuring_settings": "Настройка параметров",
        "log.config_saved": "Конфигурация сохранена в {file}",
        "log.max_threads_updated": "Количество потоков обновлено: {value}"
    },
    "en": {
        "menu.header": "CryonixSoft",
        "menu.title": "Session Checker Menu",
        "menu.start_process": "[1] Start Session Check",
        "menu.change_language": "[2] Change Language",
        "menu.configure_settings": "[3] Configure Settings",
        "menu.exit": "[4] Exit",
        "menu.select_option": "Select an option [1-4]:",
        "menu.press_enter": "Press Enter to continue...",
        "menu.starting_process": "Starting session check...",
        "menu.process_completed": "Session check completed successfully",
        "menu.process_failed": "Some sessions are unauthorized or have errors",
        "menu.goodbye": "Goodbye!",
        "menu.language_changed": "Language changed to {language}",
        "menu.select_language": "Select language",
        "menu.select_language_option": "Select option [0-2]:",
        "menu.back": "[0] Back",
        "menu.proxy_error": "Error: {error}. Proxy is required for checking.",
        "menu.no_json_files": "No JSON files found in {dir}",
        "menu.error": "Error: {error}",
        "menu.running": "Process is already running",
        "menu.config_created": "Configuration file {file} created",
        "menu.dir_created": "Directory {dir} created",
        "menu.proxy_file_created": "Proxy file {file} created",
        "menu.auth_data_missing_creating": "JSON file {file} is missing, creating a new one",
        "menu.auth_data_created": "JSON file {file} created",
        "menu.api_data_missing_generating": "API data missing in {file}, generating new",
        "menu.api_data_generated": "API data generated for {file}",
        "menu.phone_missing": "Phone number missing in {file}",
        "menu.api_data_missing": "Insufficient API data in {file}",
        "menu.session_missing": "Session for {phone} not found",
        "menu.using_proxy_old": "Using proxy: {host}:{port}",
        "menu.no_proxy_old": "No proxy used for {phone}",
        "menu.session_authorized": "Session for {phone} is authorized",
        "menu.session_not_authorized": "Session for {phone} is not authorized",
        "menu.session_file_moved": "Session file {file} moved to unauthorized_sessions",
        "menu.json_file_moved": "JSON file {file} moved to unauthorized_sessions",
        "menu.flood_limit": "Telegram API limit for {phone}, wait {seconds} seconds",
        "menu.session_unregistered": "Session for {phone} is not registered",
        "menu.session_error": "Error processing session for {phone}: {error}",
        "menu.connection_failed": "Failed to connect for {phone}: {error}",
        "menu.main_error": "An error occurred: {error}",
        "menu.current_max_threads": "Current number of threads: {value}",
        "menu.enter_max_threads": "Enter number of threads (min. 1):",
        "menu.max_threads_updated": "Number of threads updated: {value}",
        "menu.select_setting_option": "Select setting to configure [0-1]:",
        "error.proxy_empty": "proxy.txt file is empty or missing",
        "log.config_file_missing": "File {file} not found, creating with default settings",
        "log.dir_created": "Directory created: {dir}",
        "log.proxy_file_created": "Created proxy.txt file with example format",
        "log.invalid_proxy_format": "Invalid format in proxy.txt: {line}",
        "log.proxy_file_empty": "File {file} is empty, proxy is required",
        "log.auth_data_missing_creating": "JSON file {file} is missing, creating a new one",
        "log.auth_data_created": "JSON file {file} created",
        "log.api_data_missing_generating": "API data missing in {file}, generating new",
        "log.api_data_generated": "API data generated for {file}",
        "log.phone_missing": "Phone number missing in {file}",
        "log.api_data_missing": "Insufficient data in {file}: api_id or api_hash missing",
        "log.session_missing": "Session for {phone} not found",
        "log.using_proxy_old": "Using proxy: {host}:{port}",
        "log.no_proxy_old": "No proxy used for {phone}",
        "log.session_authorized": "Session for {phone} is authorized",
        "log.session_not_authorized": "Session for {phone} is not authorized",
        "log.session_file_moved": "Session file {file} moved to unauthorized_sessions",
        "log.json_file_moved": "JSON file {file} moved to unauthorized_sessions",
        "log.flood_limit": "Telegram API limit for {phone}, requires waiting {seconds} seconds",
        "log.session_unregistered": "Session for {phone} is not registered",
        "log.session_error": "Error processing session for {phone}: {error}",
        "log.connection_failed": "Failed to connect for {phone}: {error}",
        "log.changing_language": "Changing language",
        "log.language_changed": "Language changed to {language}",
        "log.option_selected": "Selected option: {choice}",
        "log.main_error": "An error occurred: {error}",
        "log.configuring_settings": "Configuring settings",
        "log.config_saved": "Configuration saved to {file}",
        "log.max_threads_updated": "Number of threads updated: {value}"
    }
}

def t(key, locale, **kwargs):
    return translations.get(locale, translations["en"]).get(key, key).format(**kwargs)